// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class BodyPart
{
    public int Id { get; set; }

    public string BodyPartName { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<CustomerConsulting> CustomerConsultings { get; set; } = new List<CustomerConsulting>();

    public virtual ICollection<PartSymptom> PartSymptoms { get; set; } = new List<PartSymptom>();
}