// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class Category : BaseEntity
{
    public string CategoryName { get; set; }

    public string Description { get; set; }

    public int? ParentCategoryId { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Category> InverseParentCategory { get; set; } = new List<Category>();

    public virtual Category ParentCategory { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}