// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class CustomerConsulting : BaseEntity
{
    public int? CustomerId { get; set; }

    public int? BodyPartId { get; set; }

    public virtual BodyPart BodyPart { get; set; }

    public virtual ICollection<ConsultingResult> ConsultingResults { get; set; } = new List<ConsultingResult>();

    public virtual User Customer { get; set; }
}