// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class Payment
{
    public int Id { get; set; }

    public string PaymentCode { get; set; }

    public DateTime? CreateDate { get; set; }

    public double? Amount { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int? OrderId { get; set; }

    public virtual Order Order { get; set; }
}