// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HimariServer.Repository.Enums;
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class Order : BaseEntity
{
    public int Id { get; set; }

    public int OrderCode { get; set; }

    public string Address { get; set; }

    public int? OrderPrice { get; set; }

    public int? UserId { get; set; }

    public DeliveryStatus DeliveryStatus { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}