// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class PartSymptom : BaseEntity
{
    public string Name { get; set; }
    public string NameUnsign { get; set; }

    public int? BodyPartId { get; set; }

    public virtual BodyPart BodyPart { get; set; }

    public virtual ICollection<ProductSymptom> ProductSymptoms { get; set; } = new List<ProductSymptom>();
}