// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HimariServer.Repository.Enums;
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class Payment : BaseEntity
{
    public double? Amount { get; set; }

    public string Description { get; set; }

    public PaymentMethod PaymentMethod { get; set; }

    public PaymentStatus Status { get; set; }

    public int? OrderId { get; set; }

    public virtual Order Order { get; set; }
}