// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class ProductSymptom : BaseEntity
{
    public int? PartSymptomId { get; set; }

    public int? ProductId { get; set; }

    public virtual PartSymptom PartSymptom { get; set; }

    public virtual Product Product { get; set; }
}