// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class Product : BaseEntity
{
    public string ProductName { get; set; }
    public string ProductNameUnsign { get; set; }

    public string Description { get; set; }

    public int? Price { get; set; }

    public int? Quantity { get; set; }

    public string ImageUrl { get; set; }

    public int? CategoryId { get; set; }

    public int? BrandId { get; set; }

    public bool? Gender { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ConsultingResult> ConsultingResults { get; set; } = new List<ConsultingResult>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<ProductSymptom> ProductSymptoms { get; set; } = new List<ProductSymptom>();
}