// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HimariServer.Repository.Entities;

public partial class User : BaseEntity
{
    public string FullName { get; set; }

    public string UnsignName { get; set; }

    public string Email { get; set; }
    public bool IsVerify { get; set; }

    public string GoogleId { get; set; }

    public string? AvatarUrl { get; set; }

    public string PhoneNumber { get; set; }

    public string Province { get; set; }
    public string District { get; set; }
    public string Ward { get; set; }
    public string AddressBonus { get; set; }

    public int? Point { get; set; }

    public int? RoleId { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<CustomerConsulting> CustomerConsultings { get; set; } = new List<CustomerConsulting>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Role Role { get; set; }

    public virtual ICollection<UserDevice> UserDevices { get; set; } = new List<UserDevice>();
}