// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using HimariServer.Repository.Entities;
using Microsoft.EntityFrameworkCore;

namespace HimariServer.Repository.DBContext;

public partial class HimariServerContext : DbContext
{
    public HimariServerContext()
    {
    }

    public HimariServerContext(DbContextOptions<HimariServerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Blog> Blogs { get; set; }
    public virtual DbSet<BlogCategory> BlogCategories { get; set; }
    public virtual DbSet<BodyPart> BodyParts { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<ConsultingResult> ConsultingResults { get; set; }

    public virtual DbSet<CustomerConsulting> CustomerConsultings { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<PartSymptom> PartSymptoms { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductSymptom> ProductSymptoms { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserDevice> UserDevices { get; set; }
    public virtual DbSet<Notification> Notifications { get; set; }
    public virtual DbSet<UserNotification> UserNotifications { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notification__3214EC0751765E13");

            entity.ToTable("Notification");

            entity.Property(e => e.Title);
            entity.Property(e => e.TitleUnsign).IsUnicode(false);

            entity.Property(n => n.Href)
            .HasMaxLength(500)
            .IsRequired(false);
            entity.Property(n => n.Type)
            .HasConversion<int>()
            .IsRequired(false);
            entity.Property(n => n.Message)
            .IsRequired(false);
        });

        modelBuilder.Entity<BlogCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BlogCategory_");
            entity.ToTable("BlogCategory");
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Blog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Blog__3214EC0751765E13");

            entity.ToTable("Blog");

            entity.Property(e => e.Content).IsUnicode(false);
            entity.Property(e => e.Title).IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.Blogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Blog__UserId__4E88ABD4");
            entity.HasOne(d => d.Category).WithMany(p => p.Blogs)
                .HasForeignKey(d => d.BlogCategoryId)
                .HasConstraintName("FK__Blog__BlogCategory__4E88ABD4");
        });

        modelBuilder.Entity<BodyPart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BodyPart__3214EC070D8B18BB");

            entity.ToTable("BodyPart");

            entity.Property(e => e.BodyPartName).IsUnicode(false);
            entity.Property(e => e.Description).IsUnicode(false);
        });

        modelBuilder.Entity<Brand>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Brand__3214EC07FDBEE05E");

            entity.ToTable("Brand");

            entity.Property(e => e.BrandName).IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.Image).HasColumnType("text");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Category__3214EC07F747C397");

            entity.ToTable("Category");

            entity.Property(e => e.CategoryName).IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory)
                .HasForeignKey(d => d.ParentCategoryId)
                .HasConstraintName("FK__Category__Parent__5FB337D6");
        });

        modelBuilder.Entity<ConsultingResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Consulti__3214EC07AE03378C");

            entity.ToTable("ConsultingResult");

            entity.HasOne(d => d.CustomerConsulting).WithMany(p => p.ConsultingResults)
                .HasForeignKey(d => d.CustomerConsultingId)
                .HasConstraintName("FK__Consultin__Custo__7C4F7684");

            entity.HasOne(d => d.Product).WithMany(p => p.ConsultingResults)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Consultin__Produ__7D439ABD");
        });

        modelBuilder.Entity<CustomerConsulting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3214EC07B8F96589");

            entity.ToTable("CustomerConsulting");

            entity.HasOne(d => d.BodyPart).WithMany(p => p.CustomerConsultings)
                .HasForeignKey(d => d.BodyPartId)
                .HasConstraintName("FK__CustomerC__BodyP__797309D9");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerConsultings)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK__CustomerC__Custo__787EE5A0");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Order__3214EC073B6A676E");

            entity.ToTable("Order");

            entity.Property(e => e.OrderCode).IsUnicode(false);

            entity.HasOne(d => d.Account).WithMany(p => p.Orders)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK__Order__AccountId__5165187F");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderDet__3214EC076368A2AF");

            entity.ToTable("OrderDetail");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__OrderDeta__Order__693CA210");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__OrderDeta__Produ__6A30C649");
        });

        modelBuilder.Entity<PartSymptom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PartSymp__3214EC070B2656E5");

            entity.ToTable("PartSymptom");

            entity.Property(e => e.Name).IsUnicode(false);

            entity.HasOne(d => d.BodyPart).WithMany(p => p.PartSymptoms)
                .HasForeignKey(d => d.BodyPartId)
                .HasConstraintName("FK__PartSympt__BodyP__71D1E811");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payment__3214EC070A0AEE9E");

            entity.ToTable("Payment");

            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.PaymentCode).IsUnicode(false);
            entity.Property(e => e.Status).IsUnicode(false);

            entity.HasOne(d => d.Order).WithMany(p => p.Payments)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__Payment__OrderId__6D0D32F4");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Product__3214EC0715285C8F");

            entity.ToTable("Product");

            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.ImageUrl).IsUnicode(false);
            entity.Property(e => e.ProductName).IsUnicode(false);

            entity.HasOne(d => d.Brand).WithMany(p => p.Products)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK__Product__BrandId__656C112C");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__Product__Categor__6477ECF3");
        });

        modelBuilder.Entity<ProductSymptom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductS__3214EC0744847958");

            entity.ToTable("ProductSymptom");

            entity.HasOne(d => d.PartSymptom).WithMany(p => p.ProductSymptoms)
                .HasForeignKey(d => d.PartSymptomId)
                .HasConstraintName("FK__ProductSy__PartS__74AE54BC");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSymptoms)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__ProductSy__Produ__75A278F5");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Role__3214EC073A531F92");

            entity.ToTable("Role");

            entity.Property(e => e.RoleName).IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC07C8A523E4");

            entity.ToTable("User");

            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.Email).IsUnicode(false);
            entity.Property(e => e.FullName).IsUnicode(false);
            entity.Property(e => e.GoogleId).IsUnicode(false);
            entity.Property(e => e.AvatarUrl).IsUnicode(false);
            entity.Property(e => e.PhoneNumber).IsUnicode(false);
            entity.Property(e => e.UnsignName).IsUnicode(false);
            entity.Property(e => e.IsVerify);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__User__RoleId__4BAC3F29");
        });

        modelBuilder.Entity<UserDevice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserDevice_");
            entity.Property(e => e.DeviceToken).IsRequired();
            entity.Property(e => e.UserId).IsRequired();
        });

        modelBuilder.Entity<UserNotification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserNotification_");
            entity.ToTable("UserNotification");
            entity.Property(un => un.IsRead)
           .HasDefaultValue(false);

            entity.HasOne(un => un.Notification) // Quan hệ với Notification
            .WithMany()
            .HasForeignKey(un => un.NotificationId);

            entity.HasOne(un => un.User) // Quan hệ với User
            .WithMany()
            .HasForeignKey(un => un.UserId);
            
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}