name: CI/CD for ASP.NET Core

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: HimariServer  # Chạy từ thư mục chứa source

      - name: Build Application
        run: dotnet build --configuration Release --no-restore
        working-directory: HimariServer

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal
        working-directory: HimariServer

      - name: Publish Application
        run: dotnet publish -c Release -o publish
        working-directory: HimariServer

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: HimariServer/publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: app  # Tải artifact vào thư mục `app`

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          scp -r app $SERVER_USER@$SERVER_IP:/var/www/app
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/app
            sudo systemctl restart kestrel-app
          EOF
